/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyLeadsRouteImport } from './routes/my-leads'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ActionsOverdueRouteImport } from './routes/actions.overdue'
import { Route as ActionsTodayRouteImport } from './routes/actions.today'
import { Route as AdminLeadRulesRouteImport } from './routes/admin.lead-rules'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSlaRulesRouteImport } from './routes/admin.sla-rules'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as PerformanceBranchRouteImport } from './routes/performance.branch'
import { Route as PerformanceExecutiveRouteImport } from './routes/performance.executive'
import { Route as ReportsClosureRouteImport } from './routes/reports.closure'
import { Route as ReportsSlaRouteImport } from './routes/reports.sla'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLeadsRoute = MyLeadsRouteImport.update({
  id: '/my-leads',
  path: '/my-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsOverdueRoute = ActionsOverdueRouteImport.update({
  id: '/actions/overdue',
  path: '/actions/overdue',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsTodayRoute = ActionsTodayRouteImport.update({
  id: '/actions/today',
  path: '/actions/today',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadRulesRoute = AdminLeadRulesRouteImport.update({
  id: '/admin/lead-rules',
  path: '/admin/lead-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlaRulesRoute = AdminSlaRulesRouteImport.update({
  id: '/admin/sla-rules',
  path: '/admin/sla-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceBranchRoute = PerformanceBranchRouteImport.update({
  id: '/performance/branch',
  path: '/performance/branch',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceExecutiveRoute = PerformanceExecutiveRouteImport.update({
  id: '/performance/executive',
  path: '/performance/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsClosureRoute = ReportsClosureRouteImport.update({
  id: '/reports/closure',
  path: '/reports/closure',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSlaRoute = ReportsSlaRouteImport.update({
  id: '/reports/sla',
  path: '/reports/sla',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/my-leads': typeof MyLeadsRoute
  '/pipeline': typeof PipelineRoute
  '/actions/overdue': typeof ActionsOverdueRoute
  '/actions/today': typeof ActionsTodayRoute
  '/admin/lead-rules': typeof AdminLeadRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sla-rules': typeof AdminSlaRulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/performance/branch': typeof PerformanceBranchRoute
  '/performance/executive': typeof PerformanceExecutiveRoute
  '/reports/closure': typeof ReportsClosureRoute
  '/reports/sla': typeof ReportsSlaRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/my-leads': typeof MyLeadsRoute
  '/pipeline': typeof PipelineRoute
  '/actions/overdue': typeof ActionsOverdueRoute
  '/actions/today': typeof ActionsTodayRoute
  '/admin/lead-rules': typeof AdminLeadRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sla-rules': typeof AdminSlaRulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/performance/branch': typeof PerformanceBranchRoute
  '/performance/executive': typeof PerformanceExecutiveRoute
  '/reports/closure': typeof ReportsClosureRoute
  '/reports/sla': typeof ReportsSlaRoute
  '/leads': typeof LeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/my-leads': typeof MyLeadsRoute
  '/pipeline': typeof PipelineRoute
  '/actions/overdue': typeof ActionsOverdueRoute
  '/actions/today': typeof ActionsTodayRoute
  '/admin/lead-rules': typeof AdminLeadRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sla-rules': typeof AdminSlaRulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/performance/branch': typeof PerformanceBranchRoute
  '/performance/executive': typeof PerformanceExecutiveRoute
  '/reports/closure': typeof ReportsClosureRoute
  '/reports/sla': typeof ReportsSlaRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/escalations'
    | '/login'
    | '/my-leads'
    | '/pipeline'
    | '/actions/overdue'
    | '/actions/today'
    | '/admin/lead-rules'
    | '/admin/settings'
    | '/admin/sla-rules'
    | '/admin/users'
    | '/leads/$leadId'
    | '/performance/branch'
    | '/performance/executive'
    | '/reports/closure'
    | '/reports/sla'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/escalations'
    | '/login'
    | '/my-leads'
    | '/pipeline'
    | '/actions/overdue'
    | '/actions/today'
    | '/admin/lead-rules'
    | '/admin/settings'
    | '/admin/sla-rules'
    | '/admin/users'
    | '/leads/$leadId'
    | '/performance/branch'
    | '/performance/executive'
    | '/reports/closure'
    | '/reports/sla'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/escalations'
    | '/login'
    | '/my-leads'
    | '/pipeline'
    | '/actions/overdue'
    | '/actions/today'
    | '/admin/lead-rules'
    | '/admin/settings'
    | '/admin/sla-rules'
    | '/admin/users'
    | '/leads/$leadId'
    | '/performance/branch'
    | '/performance/executive'
    | '/reports/closure'
    | '/reports/sla'
    | '/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EscalationsRoute: typeof EscalationsRoute
  LoginRoute: typeof LoginRoute
  MyLeadsRoute: typeof MyLeadsRoute
  PipelineRoute: typeof PipelineRoute
  ActionsOverdueRoute: typeof ActionsOverdueRoute
  ActionsTodayRoute: typeof ActionsTodayRoute
  AdminLeadRulesRoute: typeof AdminLeadRulesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSlaRulesRoute: typeof AdminSlaRulesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  PerformanceBranchRoute: typeof PerformanceBranchRoute
  PerformanceExecutiveRoute: typeof PerformanceExecutiveRoute
  ReportsClosureRoute: typeof ReportsClosureRoute
  ReportsSlaRoute: typeof ReportsSlaRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-leads': {
      id: '/my-leads'
      path: '/my-leads'
      fullPath: '/my-leads'
      preLoaderRoute: typeof MyLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/overdue': {
      id: '/actions/overdue'
      path: '/actions/overdue'
      fullPath: '/actions/overdue'
      preLoaderRoute: typeof ActionsOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/today': {
      id: '/actions/today'
      path: '/actions/today'
      fullPath: '/actions/today'
      preLoaderRoute: typeof ActionsTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lead-rules': {
      id: '/admin/lead-rules'
      path: '/admin/lead-rules'
      fullPath: '/admin/lead-rules'
      preLoaderRoute: typeof AdminLeadRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sla-rules': {
      id: '/admin/sla-rules'
      path: '/admin/sla-rules'
      fullPath: '/admin/sla-rules'
      preLoaderRoute: typeof AdminSlaRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/branch': {
      id: '/performance/branch'
      path: '/performance/branch'
      fullPath: '/performance/branch'
      preLoaderRoute: typeof PerformanceBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/executive': {
      id: '/performance/executive'
      path: '/performance/executive'
      fullPath: '/performance/executive'
      preLoaderRoute: typeof PerformanceExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/closure': {
      id: '/reports/closure'
      path: '/reports/closure'
      fullPath: '/reports/closure'
      preLoaderRoute: typeof ReportsClosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sla': {
      id: '/reports/sla'
      path: '/reports/sla'
      fullPath: '/reports/sla'
      preLoaderRoute: typeof ReportsSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EscalationsRoute: EscalationsRoute,
  LoginRoute: LoginRoute,
  MyLeadsRoute: MyLeadsRoute,
  PipelineRoute: PipelineRoute,
  ActionsOverdueRoute: ActionsOverdueRoute,
  ActionsTodayRoute: ActionsTodayRoute,
  AdminLeadRulesRoute: AdminLeadRulesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSlaRulesRoute: AdminSlaRulesRoute,
  AdminUsersRoute: AdminUsersRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  PerformanceBranchRoute: PerformanceBranchRoute,
  PerformanceExecutiveRoute: PerformanceExecutiveRoute,
  ReportsClosureRoute: ReportsClosureRoute,
  ReportsSlaRoute: ReportsSlaRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
